export const siteConfig = {
	name: 'Aditya Bhaskar Sharma',
	role: 'Product Engineer',
	shortName: 'adi.codes',
	title: 'Aditya Bhaskar Sharma — Product Engineer · iOS, React Native & Web',
	description:
		'Product engineer with 13+ years of experience shipping iOS apps (Swift, SwiftUI), React Native, and full-stack web products (Next.js, Laravel, TypeScript). I own the whole loop — product decisions, architecture, code, and App Store releases. Founder of LazyCodeLab. Available for senior engineering roles and contract work, remote.',
	url: 'https://adi.codes',
	baseKeywords: [
		'Aditya Bhaskar Sharma',
		'product engineer',
		'senior product engineer',
		'product engineer portfolio',
		'software engineer portfolio',
		'senior software engineer',
		'iOS engineer',
		'iOS developer',
		'Swift developer',
		'SwiftUI',
		'React Native developer',
		'Next.js developer',
		'full-stack engineer',
		'TypeScript engineer',
		'Laravel developer',
		'Shopify developer',
		'indie app developer',
		'remote software engineer India',
		'hire product engineer',
	],
	email: 'adityabhaskarsharma@gmail.com',
	image: '/assets/images/adi-new.png',
	resume: '/assets/resume/mobile-resume-latest.pdf',
	social: {
		linkedin: 'https://linkedin.com/in/-abs-',
		twitter: 'https://threads.com/adictonator',
		instagram: 'https://instagram.com/adictonator',
		github: 'https://github.com/adictonator',
	},
	sameAs: [
		'https://linkedin.com/in/-abs-',
		'https://github.com/adictonator',
		'https://threads.com/adictonator',
		'https://instagram.com/adictonator',
		'https://lazycodelab.com',
	],
} as const
